// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "./(frontend)/providers/AuthProvider";
import "./globals.css";
import { getServerSession } from "next-auth";
import {authOptions} from "./api/auth/[...nextauth]/route"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body
        // --- BASE DARK MODE STYLES ADDED HERE ---
        // 1. Set the background to a deep dark grey (consistent with your theme)
        // 2. Set the default text color to white/light grey
        // 3. Ensure the min-height of the body is set to fill the viewport
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-gray-100 min-h-screen`}
        // --------------------------------------
      ><AuthProvider session={session}>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}